name: Run tests
# Run this workflow whenever something new is pushed.
on: push
jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest

      - name: Log in with SSH Key to remote server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PASSWORD }}
          ARGS: 'whoami'
          HOST: ${{ secrets.HOSTNAME }}
          USERNAME: ${{ secrets.USERNAME }}
          
