name: Run tests
# Run this workflow whenever something new is pushed.
on: push
jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.4.0
        with:
          ssh-private-key: ${{ secrets.ASSIGNMENT }}
      - name: Login to Remote Server (if tests pass)
        if: ${{ success() }}
        run: ssh user@hostname 'whoami'
          
