name: Run tests
# Run this workflow whenever something new is pushed.
on: push
jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest

      - name: Login to Remote Server (if tests pass)
        run: |
          echo "$ASSIGNMENT"
        env:
          ASSIGNMENT: ${{secrets.ASSIGNMENT}}
          
