name: Run tests
# Run this workflow whenever something new is pushed.
on:
  push:
   branches:
     - "main"

jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest


      - name: Log in to remote server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PASS }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/cd-assignment
            git pull
            sudo systemctl restart cd-assignment.service
