name: Run tests

# Run this workflow whenever something new is pushed.
on: push
jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        # Specify some input for this particular action
        with:
          python-version: '3.8.10'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest

      - name: Login to Remote Server (if tests pass)
        env:
          ASSIGNMENT:${{secrets.ASSIGNMENT}}

        # uses: appleboy/ssh-action@master
        # with:
        #   host: ${{ env.REMOTE_SERVER }}
        #   username: ${{ env.USERNAME }}
        #   password: ${{ secrets.PASSWORD }}
        #   private_key: ${{ secrets.SUPER_SECRET }}  